config/routes.rb
DeviseProject::Application.routes.draw do
  devise_for :users

  resources :diary_entries, :only => [:create, :index, :new, :show, :destroy]

  root :to => 'static_pages#home'
end

app/models/diary_entry.rb
class DiaryEntry < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :diary_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json

  def index
    @user = current_user
    @entries = @user.diary_entries

    respond_with(@entries)
  end

  def show
    @entry = DiaryEntry.find(params[:id])
    if @entry.user == current_user
      respond_with(@entry)
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def new
    @diary_entry = DiaryEntry.new
  end

  def create
    @diary_entry = DiaryEntry.new(params[:diary_entry])
    @diary_entry.user_id = current_user.id

    if @diary_entry.save
      respond_with(@diary_entry)
    end
  end

  def destroy
    @diary_entry = DiaryEntry.find(params[:id])
    if @diary_entry.user == current_user
      @diary_entry.destroy

      redirect_to(diary_entries_path)
    else
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diary_entries_helper.rb
module DiaryEntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/diary_entries/index.html.haml
%ul
  - for entry in @entries
    %li
      #{entry.title} #{link_to "Destroy", diary_entry_path(entry), :method => :delete }

app/views/diary_entries/new.html.haml
= simple_form_for(@diary_entry) do |f|
  = f.input :title

  = f.button :submit, :value => "Submit!"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= render "shared/user_controls" %>
  <% else %>
    <%= link_to "sign in!", new_user_session_path %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/shared/_user_controls.html.haml
= link_to "sign out!", destroy_user_session_path, :method => :delete

app/views/static_pages/home.html.haml
%p
  Welcome to my authenticated web page!